/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package faculpro;

import cjb.ci.Mensaje;
import faculpro.Nodo;
import facultades.*;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author PARRA
 */
public class Principal extends javax.swing.JFrame {

    public static Nodo r;
    public static Nodo actual;
    public static int tipo = 0; //0 facultad,1 carrera,2 materia, 3 grupo, 4 alumno     
    public static String s[];

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        //cjb.ci.CtrlInterfaz.habilita(false,txtnomfac,txtidfac,txtdirfac,txtcurricar,txtnomcar,txtidcar,txtabreviacarr,txtnommat,txtcredmat,txtsemesmat,txtidgrup,
        //                txthorasgrup,txtdiasgrup,txtnomalum,txtmatalum,txtsemesalum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTArbol = new javax.swing.JTree();
        btnaltas = new javax.swing.JButton();
        btnbajas = new javax.swing.JButton();
        btnmodifica = new javax.swing.JButton();
        txtnbusca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jpfacultad = new javax.swing.JPanel();
        txtnomfac = new javax.swing.JTextField();
        txtidfac = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdirfac = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jpcarrera = new javax.swing.JPanel();
        txtnomcar = new javax.swing.JTextField();
        txtidcar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcurricar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtabreviacarr = new javax.swing.JTextField();
        jpmateria = new javax.swing.JPanel();
        txtnommat = new javax.swing.JTextField();
        txtcredmat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtsemesmat = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jp = new javax.swing.JPanel();
        txtidgrup = new javax.swing.JTextField();
        txtdiasgrup = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txthorasgrup = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtnomalum = new javax.swing.JTextField();
        txtmatrialum = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtsemesalum = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtpruebas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTArbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTArbolMousePressed(evt);
            }
        });
        jTArbol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTArbolKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTArbol);

        btnaltas.setText("Alta");
        btnaltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaltasActionPerformed(evt);
            }
        });

        btnbajas.setText("Baja");
        btnbajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbajasActionPerformed(evt);
            }
        });

        btnmodifica.setText("Modifica");
        btnmodifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificaActionPerformed(evt);
            }
        });

        jLabel1.setText("Busqueda");

        txtnomfac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomfacActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre ");

        jLabel3.setText("Clave");

        jLabel4.setText("Direccion");

        jLabel5.setText("FACULTAD");

        javax.swing.GroupLayout jpfacultadLayout = new javax.swing.GroupLayout(jpfacultad);
        jpfacultad.setLayout(jpfacultadLayout);
        jpfacultadLayout.setHorizontalGroup(
            jpfacultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfacultadLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jpfacultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpfacultadLayout.createSequentialGroup()
                        .addGroup(jpfacultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jpfacultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidfac, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(txtnomfac)
                            .addComponent(txtdirfac))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpfacultadLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(79, 79, 79))))
        );
        jpfacultadLayout.setVerticalGroup(
            jpfacultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfacultadLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpfacultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnomfac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpfacultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtidfac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpfacultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdirfac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtnomcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomcarActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre ");

        jLabel7.setText("Clave");

        jLabel8.setText("Curricula");

        jLabel9.setText("CARRERA");

        jLabel10.setText("Abreviatura");

        javax.swing.GroupLayout jpcarreraLayout = new javax.swing.GroupLayout(jpcarrera);
        jpcarrera.setLayout(jpcarreraLayout);
        jpcarreraLayout.setHorizontalGroup(
            jpcarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpcarreraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpcarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpcarreraLayout.createSequentialGroup()
                        .addGroup(jpcarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jpcarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidcar)
                            .addComponent(txtnomcar)
                            .addComponent(txtcurricar)
                            .addComponent(txtabreviacarr, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpcarreraLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(79, 79, 79))))
        );
        jpcarreraLayout.setVerticalGroup(
            jpcarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpcarreraLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpcarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnomcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpcarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtidcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpcarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtcurricar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpcarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtabreviacarr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtnommat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnommatActionPerformed(evt);
            }
        });

        jLabel16.setText("Nombre ");

        jLabel17.setText("Creditos");

        jLabel18.setText("Semestre");

        jLabel19.setText("MATERIA");

        javax.swing.GroupLayout jpmateriaLayout = new javax.swing.GroupLayout(jpmateria);
        jpmateria.setLayout(jpmateriaLayout);
        jpmateriaLayout.setHorizontalGroup(
            jpmateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmateriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpmateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpmateriaLayout.createSequentialGroup()
                        .addGroup(jpmateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jpmateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcredmat, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(txtnommat)
                            .addComponent(txtsemesmat))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpmateriaLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(79, 79, 79))))
        );
        jpmateriaLayout.setVerticalGroup(
            jpmateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmateriaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpmateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnommat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpmateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtcredmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpmateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtsemesmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        txtidgrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidgrupActionPerformed(evt);
            }
        });

        jLabel20.setText("Clave");

        jLabel21.setText("Dias ");

        jLabel22.setText("Horas");

        jLabel23.setText("GRUPO");

        javax.swing.GroupLayout jpLayout = new javax.swing.GroupLayout(jp);
        jp.setLayout(jpLayout);
        jpLayout.setHorizontalGroup(
            jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidgrup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiasgrup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthorasgrup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
            .addGroup(jpLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpLayout.setVerticalGroup(
            jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidgrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtdiasgrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txthorasgrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtnomalum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomalumActionPerformed(evt);
            }
        });

        jLabel24.setText("Nombre ");

        jLabel25.setText("Matricula");

        jLabel26.setText("Semestre");

        jLabel27.setText("ALUMNO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmatrialum, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(txtnomalum)
                            .addComponent(txtsemesalum))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(79, 79, 79))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnomalum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtmatrialum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtsemesalum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtpruebas.setColumns(20);
        txtpruebas.setRows(5);
        jScrollPane2.setViewportView(txtpruebas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpcarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpfacultad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpmateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtnbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnaltas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(170, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnbajas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnmodifica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jp, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtnbusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(8, 8, 8))
                            .addComponent(jpfacultad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jpcarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpmateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(btnbajas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnmodifica, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        r = ManipulaListas.carga(this);
        ActualizaArbol();

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void btnaltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaltasActionPerformed
        switch (tipo+1) {
            case 0:
                if (Mensaje.pregunta(this, "¿Quiere dar de alta a: " + txtnomfac.getText() + "?") == JOptionPane.YES_OPTION) {
                    String[] s = {txtnomfac.getText()};
                    r = ManipulaListas.inserta(r, s, 0, new Nodo(txtnomfac.getText(), new Facultad(txtnomfac.getText(), Integer.parseInt(txtidfac.getText()), txtdirfac.getText())), null);
                    Mensaje.exito(this, txtnomfac.getText() + " Agregado");
                }
                break;
            case 1:
                if (Mensaje.pregunta(this, "¿Quiere dar de alta a: " + txtnomcar.getText() + "?") == JOptionPane.YES_OPTION) {
                    String[] s = {txtnomfac.getText(), txtnomcar.getText()};
                    r = ManipulaListas.inserta(r, s, 0, new Nodo(txtnomcar.getText(), new Carrera(txtnomcar.getText(), Integer.parseInt(txtidcar.getText()), Integer.parseInt(txtcurricar.getText()), txtabreviacarr.getText())), null);
                    Mensaje.exito(this, txtnomcar.getText() + " Agregado");
                }
                break;
            case 2:
                if (Mensaje.pregunta(this, "¿Quiere dar de alta a: " + txtnommat.getText() + "?") == JOptionPane.YES_OPTION) {
                    String[] s = {txtnomfac.getText(), txtnomcar.getText(), txtnommat.getText()};
                    r = ManipulaListas.inserta(r, s, 0, new Nodo(txtnommat.getText(), new Materia(txtnommat.getText(), Integer.parseInt(txtcredmat.getText()), Integer.parseInt(txtsemesmat.getText()))), null);
                    Mensaje.exito(this, txtnommat.getText() + " Agregado");
                }
                break;
            case 3:
                if (Mensaje.pregunta(this, "¿Quiere dar de alta a: " + txtidgrup.getText() + "?") == JOptionPane.YES_OPTION) {
                    String[] s = {txtnomfac.getText(), txtnomcar.getText(), txtnommat.getText(), txtidgrup.getText()};
                    r = ManipulaListas.inserta(r, s, 0, new Nodo(txtidgrup.getText(), new Grupo(txtidgrup.getText(), txtdiasgrup.getText(), txthorasgrup.getText())), null);
                    Mensaje.exito(this, txtidgrup.getText() + " Agregado");
                }
                break;
            case 4:
                if (Mensaje.pregunta(this, "¿Quiere dar de alta a: " + txtnomalum.getText() + "?") == JOptionPane.YES_OPTION) {
                    String[] s = {txtnomfac.getText(), txtnomcar.getText(), txtnommat.getText(), txtidgrup.getText(), txtnomalum.getText()};
                    r = ManipulaListas.inserta(r, s, 0, new Nodo(txtnomalum.getText(), new Alumno(txtnomalum.getText(), Integer.parseInt(txtmatrialum.getText()), Integer.parseInt(txtsemesalum.getText()) )), null);
                    Mensaje.exito(this, txtnomalum.getText() + " Agregado");
                }
                break;
        }
        ActualizaArbol();
    }//GEN-LAST:event_btnaltasActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ManipulaListas.guarda(r, this);
    }//GEN-LAST:event_formWindowClosing

    private void btnbajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbajasActionPerformed
        TreePath ruta = jTArbol.getSelectionPath();
        s=Borra(ruta);
        if (Mensaje.pregunta(this, "seguro que desea eliminar"+s[s.length-1])==JOptionPane.YES_OPTION) {
            Nodo x[];
            x=ManipulaListas.elimina(r, s, 0,actual);
            r=x[0];
            Mensaje.exito(this, x[1].getEtiqueta()+" Eliminado");
            ActualizaArbol();
        }
    }//GEN-LAST:event_btnbajasActionPerformed

    private void btnmodificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificaActionPerformed
        switch (tipo) {
            case 0:
                if (Mensaje.pregunta(this, "¿Quiere Modificar a: " + txtnomfac.getText() + "?") == JOptionPane.YES_OPTION) {
                    ((Facultad)actual.getObj()).setDir(txtdirfac.getText());
                    Mensaje.exito(this, txtnomfac.getText() + " Modificada");
                }
                break;
            case 1:
                if (Mensaje.pregunta(this, "¿Quiere Modificar a: " + txtnomcar.getText() + "?") == JOptionPane.YES_OPTION) {
                    ((Carrera)actual.getObj()).setAbreviatura(txtabreviacarr.getText());
                    ((Carrera)actual.getObj()).setCurricula(Integer.parseInt(txtcurricar.getText()));
                    ((Carrera)actual.getObj()).setClavefac(Integer.parseInt(txtidcar.getText()));
                    Mensaje.exito(this, txtnomcar.getText() + " Modificado");
                }
                break;
            case 2:
                if (Mensaje.pregunta(this, "¿Quiere Modificar a: " + txtnommat.getText() + "?") == JOptionPane.YES_OPTION) {
                    ((Materia)actual.getObj()).setCreditos(Integer.parseInt(txtcredmat.getText()));
                    ((Materia)actual.getObj()).setSemestre(Integer.parseInt(txtsemesmat.getText()));
                    Mensaje.exito(this, txtnommat.getText() + " Modificado");
                }
                break;
            case 3:
                if (Mensaje.pregunta(this, "¿Quiere dar de alta a: " + txtidgrup.getText() + "?") == JOptionPane.YES_OPTION) {
                    ((Grupo)actual.getObj()).setDia(txtdiasgrup.getText());
                    ((Grupo)actual.getObj()).setHoras(txthorasgrup.getText());
                    Mensaje.exito(this, txtidgrup.getText() + " Modificado");
                }
                break;
            case 4:
                if (Mensaje.pregunta(this, "¿Quiere Modifificar a: " + txtnomalum.getText() + "?") == JOptionPane.YES_OPTION) {
                    ((Alumno)actual.getObj()).setSemestrealu(Integer.parseInt(txtsemesalum.getText()));
                    Mensaje.exito(this, txtnomalum.getText() + " Modificado");
                }
                break;
        }
        ActualizaArbol();
    
    }//GEN-LAST:event_btnmodificaActionPerformed

    private void txtnomfacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomfacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomfacActionPerformed

    private void txtnomcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomcarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomcarActionPerformed

    private void txtnommatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnommatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnommatActionPerformed

    private void txtidgrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidgrupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidgrupActionPerformed

    private void txtnomalumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomalumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomalumActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        txtpruebas.setText(String.valueOf(jTArbol.getSelectionCount()));

//        TreePath ruta = jTArbol.getSelectionPath();
//        String n[]=Borra(ruta);
//        String p="";
//        for (int i = 0; i < n.length; i++) {
//            p+=n[i]+"\n";
//        }
//        txtpruebas.setText(p);
//        Nodo aux = r;
//        String s1 = "";
//        do {
//            s1 += aux.getEtiqueta() + "\n";
//            aux = aux.getSiguiente();
//        } while (!(aux.getEtiqueta().equals(r.getEtiqueta())));
//        txtpruebas.setText("");
//        txtpruebas.setText(s1);
//
//        System.out.println("me lleva la chingada");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTArbolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTArbolMousePressed
        Actualiza();
    }//GEN-LAST:event_jTArbolMousePressed

    private void jTArbolKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTArbolKeyReleased
        Actualiza();
        
    }//GEN-LAST:event_jTArbolKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaltas;
    private javax.swing.JButton btnbajas;
    private javax.swing.JButton btnmodifica;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTArbol;
    private javax.swing.JPanel jp;
    private javax.swing.JPanel jpcarrera;
    private javax.swing.JPanel jpfacultad;
    private javax.swing.JPanel jpmateria;
    private javax.swing.JTextField txtabreviacarr;
    private javax.swing.JTextField txtcredmat;
    private javax.swing.JTextField txtcurricar;
    private javax.swing.JTextField txtdiasgrup;
    private javax.swing.JTextField txtdirfac;
    private javax.swing.JTextField txthorasgrup;
    private javax.swing.JTextField txtidcar;
    private javax.swing.JTextField txtidfac;
    private javax.swing.JTextField txtidgrup;
    private javax.swing.JTextField txtmatrialum;
    private javax.swing.JTextField txtnbusca;
    private javax.swing.JTextField txtnomalum;
    private javax.swing.JTextField txtnomcar;
    private javax.swing.JTextField txtnomfac;
    private javax.swing.JTextField txtnommat;
    private javax.swing.JTextArea txtpruebas;
    private javax.swing.JTextField txtsemesalum;
    private javax.swing.JTextField txtsemesmat;
    // End of variables declaration//GEN-END:variables

    public void ActualizaArbol() {
        //jTArbol = null;
        //jTArbol = new JTree();
        Nodo aux = r.getSiguiente();

        DefaultMutableTreeNode Instituciones = new DefaultMutableTreeNode("Facultades");
        if (aux == null) {
            Mensaje.error(this, "Listas vacias");
        } else {
            do {
                DefaultMutableTreeNode Facu;
                if (((Facultad) aux.getObj()).getClavefac() < 10) {
                    Facu = new DefaultMutableTreeNode("0" + Integer.toString(((Facultad) aux.getObj()).getClavefac()) + ".- " + aux.getEtiqueta());
                } else {
                    Facu = new DefaultMutableTreeNode(Integer.toString(((Facultad) aux.getObj()).getClavefac()) + ".- " + aux.getEtiqueta());
                }
                Instituciones.add(Facu);
                Nodo carAux = aux.getAbajo();
                do {
                    if (carAux == null) {
                        break;
                    }
                    DefaultMutableTreeNode Carrera = new DefaultMutableTreeNode(carAux.getEtiqueta());
                    Facu.add(Carrera);
                    Nodo matAux = carAux.getAbajo();
                    do {
                        if (matAux == null) {
                            break;
                        }
                        DefaultMutableTreeNode Materia = new DefaultMutableTreeNode(matAux.getEtiqueta());
                        Carrera.add(Materia);
                        Nodo gpoAux = matAux.getAbajo();
                        do {
                            if (gpoAux == null) {
                                break;
                            }
                            DefaultMutableTreeNode Grupo = new DefaultMutableTreeNode(gpoAux.getEtiqueta());
                            Materia.add(Grupo);
                            Nodo aluAux = gpoAux.getAbajo();
                            do {
                                if (aluAux == null) {
                                    break;
                                }
                                DefaultMutableTreeNode Alumno = new DefaultMutableTreeNode(aluAux.getEtiqueta());
                                Grupo.add(Alumno);
                                aluAux = aluAux.getAnterior();
                            } while (aluAux != gpoAux.getAbajo());
                            gpoAux = gpoAux.getAnterior();
                        } while (gpoAux != matAux.getAbajo());
                        matAux = matAux.getAnterior();
                    } while (matAux != carAux.getAbajo());
                    carAux = carAux.getAnterior();
                } while (carAux != aux.getAbajo());
                aux = aux.getSiguiente();

            } while (aux != r);
            jTArbol.setModel(new DefaultTreeModel(Instituciones));
        }
    }

    public static String[] Borra(TreePath n) {//Obtiene ruta
        String p[] = new String[n.getPath().length - 1];
        
        if (n==null) {
            System.out.println("null");
        }else{
        

        for (int i = 1; i < n.getPath().length; i++) {
            if (i != 1 ) {
                p[i - 1] = String.valueOf(n.getPath()[i]);
            } else {
                if (i == 1) {
                    p[i - 1] = String.valueOf(n.getPath()[i]).substring(5);
                } 
//                else {
//                    p[i - 1] = String.valueOf(n.getPath()[i]).substring(6);
//                }
            }
        }    
        }
        
        return p;
    }

    public void Actualiza() {
        TreePath ruta = jTArbol.getSelectionPath();
        s = Borra(ruta);
        actual = ManipulaListas.busca(r, s, 0);
        if (actual == null) {
            System.out.println("nuloooo");
        } else {

            if (actual.getObj() instanceof Facultad) {
                tipo = 0;
                Facultad act = (Facultad) actual.getObj();
                txtnomfac.setText(act.getNomfacul());
                txtidfac.setText(String.valueOf(act.getClavefac()));
                txtdirfac.setText(act.getDir());
                cjb.ci.CtrlInterfaz.limpia(txtnomcar,txtidcar,txtabreviacarr,txtnommat,txtcredmat,txtsemesmat,txtidgrup,
                        txthorasgrup,txtdiasgrup,txtnomalum,txtmatrialum,txtsemesalum);
                txtpruebas.setText(act.desp());
            } else {
                if (actual.getObj() instanceof Carrera) {
                    tipo = 1;
                    Carrera act = (Carrera) actual.getObj();
                    txtnomcar.setText(act.getNomCarr());
                    txtidcar.setText(String.valueOf(act.getCurricula()));
                    txtabreviacarr.setText(act.getAbreviatura());
                    cjb.ci.CtrlInterfaz.limpia(txtnommat,txtcredmat,txtsemesmat,txtidgrup,
                        txthorasgrup,txtdiasgrup,txtnomalum,txtmatrialum,txtsemesalum);
                    txtpruebas.setText(act.desp());
                } else {
                    if (actual.getObj() instanceof Materia) {
                        tipo = 2;
                        Materia act = (Materia) actual.getObj();
                        txtnommat.setText(act.getNommateria());
                        txtcredmat.setText(String.valueOf(act.getCreditos()));
                        txtsemesmat.setText(String.valueOf(act.getSemestre()));
                        cjb.ci.CtrlInterfaz.limpia(txtidgrup,
                        txthorasgrup,txtdiasgrup,txtnomalum,txtmatrialum,txtsemesalum);
                        txtpruebas.setText(act.desp());
                    } else {
                        if (actual.getObj() instanceof Grupo) {
                            tipo = 3;
                            Grupo act = (Grupo) actual.getObj();
                            txtidgrup.setText(act.getClavegrupo());
                            txthorasgrup.setText(act.getHoras());
                            txtdiasgrup.setText(act.getDia());
                            cjb.ci.CtrlInterfaz.limpia(txtnomalum,txtmatrialum,txtsemesalum);
                            txtpruebas.setText(act.desp());
                        }
//                        } else {
//                            if (actual.getObj() instanceof Alumno) {
//                                Mensaje.exito(this, "entrando a alumnos");
//                                tipo = 5;
//                                Alumno act = (Alumno) actual.getObj();
//                                txtnomalum.setText(act.getNomalumno());
//                                txtmatalum.setText(String.valueOf(act.getMatricula()));
//                                txtsemesalum.setText(String.valueOf(act.getSemestrealu()));
//                                txtpruebas.setText(act.desp());
//                            }
//                        }
                    }
                }
            }
        }
    }
}
